work with code tableViewCell
Neevetal/WhereToGo pull request #6
Opened 2021-05-17 03:55 UTC by Neevetal

2021-05-17 06:19 UTC, jsyrtsov requested changes

2021-05-17 06:19 UTC, jsyrtsov commented on WhereToGo/WhereToGo/UserStories/MainViewController/MainTableViewCell.swift
> +    @IBOutlet private weak var imageMain: UIImageView!
добавь MARKи

2021-05-17 06:19 UTC, jsyrtsov commented on WhereToGo/WhereToGo/UserStories/MainViewController/MainTableViewCell.swift
> +    @IBOutlet private weak var labelMain: UILabel!
нужны более обдуманные названия для аутлетов. отображающие суть

2021-05-17 06:19 UTC, jsyrtsov commented on WhereToGo/WhereToGo/UserStories/MainViewController/MainTableViewCell.swift
> +        // Configure the view for the selected state
если метод не используешь - удаляй

2021-05-17 06:19 UTC, jsyrtsov commented on WhereToGo/WhereToGo/UserStories/MainViewController/ViewController.swift
> +    let idCell = "mainCell"
private let , это наша закрытая проперти, никому она больше не нужна

2021-05-17 06:19 UTC, jsyrtsov commented on WhereToGo/WhereToGo/UserStories/MainViewController/ViewController.swift
>      override func viewDidLoad() {
тоже расставь MARKи

2021-05-17 06:19 UTC, jsyrtsov commented on WhereToGo/WhereToGo/UserStories/MainViewController/ViewController.swift
> +        tableView.dataSource = self
все что связано с настройкой таблицы выдели в отдельный метод в духе 
private func configureTableView() {}

2021-05-17 06:19 UTC, jsyrtsov commented on WhereToGo/WhereToGo/UserStories/MainViewController/ViewController.swift
> +        return 3
почитай что такое магические числа и избавься от них

2021-05-17 06:19 UTC, jsyrtsov commented on WhereToGo/WhereToGo/UserStories/MainViewController/ViewController.swift
> +        return 100.0
этот метод вообще не используем. у нас высоту ячейки считает auto layout, а тут ты сам зачем-то сидишь высчитываешь сколько высотой должна получиться ячейка

2021-05-22 16:01 UTC, Neevetal commented on WhereToGo/WhereToGo/UserStories/MainViewController/MainTableViewCell.swift
> +    @IBOutlet private weak var labelMain: UILabel!
исправил

2021-05-22 16:01 UTC, Neevetal commented on WhereToGo/WhereToGo/UserStories/MainViewController/MainTableViewCell.swift
> +    @IBOutlet private weak var imageMain: UIImageView!
сделал

2021-05-22 16:02 UTC, Neevetal commented on WhereToGo/WhereToGo/UserStories/MainViewController/ViewController.swift
> +        return 3
я понял что нельзя использовать целые числа, но заменить пока не могу понять как (прописать в коде)

2021-05-22 16:03 UTC, Neevetal commented on WhereToGo/WhereToGo/UserStories/MainViewController/ViewController.swift
> +        tableView.dataSource = self
попробовал
в биде выдает просто пустые строки

2021-05-22 16:04 UTC, closed without merging